import assert from "node:assert/strict"; import test from "node:test"; import { authorizationRequestSchema, type AuthorizationRequest, type ZcosPrincipal } from "./contracts"; import { computeApprovalScopeHash, computeAuthorizationScopeHash, evaluateAuthorization, signApproval, signAuthorizationGrant, signCapabilityCertification, signIsolationAttestation } from "./authorization-engine";
const now = new Date("2026-08-24T09:00:00.000Z"), gs="grant-secret", as="approval-secret", cs="cert-secret", is="isolation-secret";
const principal: ZcosPrincipal = { ownerId:"owner-123",actorId:"actor-123",roles:["zcos-execution"],scopes:["files:read","provider:send"],authenticatedAt:now.toISOString(),nonce:"nonce-12345678",authenticationMethod:"ZCOS_GATEWAY" };
function make(overrides: Partial<AuthorizationRequest> = {}): AuthorizationRequest { const capability=overrides.capability??"files:read"; const cert={certificationId:`cert-${capability}`,capability,state:"CERTIFIED" as const,version:"1",certifiedAt:"2026-08-24T08:00:00.000Z",expiresAt:"2026-08-25T09:00:00.000Z"}; const candidate={requestId:"request-1",traceId:"trace-1",ownerId:"owner-123",galaxy:"ZENITH",capability,operation:"READ" as const,resourceRefs:["file://artifact-1"],destination:{kind:"INTERNAL" as const,ref:"internal://zenith/files"},affectedData:"CONFIDENTIAL" as const,reversibility:"REVERSIBLE" as const,sideEffectClass:"NONE" as const,executionBinding:{method:"POST" as const,path:"/api/files/read",bodyHash:"b".repeat(64)},certification:{...cert,signature:signCapabilityCertification(cs,cert)},requiredScopes:["files:read"],idempotencyKey:"idempotency-1",credentialReferences:[],untrustedInputs:[],...overrides}; if(overrides.grant) return authorizationRequestSchema.parse(candidate); const grant={grantId:"grant-1",ownerId:"owner-123",version:"1",authorizedScopeHash:computeAuthorizationScopeHash(candidate),scopes:["files:read","provider:send"],issuedAt:"2026-08-24T08:00:00.000Z",expiresAt:"2026-08-25T09:00:00.000Z",revoked:false}; return authorizationRequestSchema.parse({...candidate,grant:{...grant,signature:signAuthorizationGrant(gs,grant)}}); }
function isolation(){const x={kind:"PROVIDER" as const,boundaryId:"boundary-1",ephemeral:true,networkPolicy:"PROVIDER_ONLY" as const,attestedAt:"2026-08-24T08:59:00.000Z",expiresAt:"2026-08-24T09:10:00.000Z"};return {...x,signature:signIsolationAttestation(is,x)}}
test.beforeEach(()=>{process.env.ZCOS_GRANT_SIGNING_SECRET=gs;process.env.ZCOS_APPROVAL_SIGNING_SECRET=as;process.env.ZCOS_CAPABILITY_SIGNING_SECRET=cs;process.env.ZCOS_ISOLATION_SIGNING_SECRET=is;});
test("allows certified same-owner read",()=>assert.equal(evaluateAuthorization(principal,make(),now).decision,"ALLOW"));
test("blocks cross-owner",()=>assert.equal(evaluateAuthorization(principal,make({ownerId:"owner-456"}),now).decision,"BLOCK"));
test("requires approval for provider send",()=>assert.equal(evaluateAuthorization(principal,make({capability:"provider:send",operation:"SEND",destination:{kind:"PROVIDER",ref:"provider://messages"},sideEffectClass:"NON_IDEMPOTENT",requiredScopes:["provider:send"],isolation:isolation()}),now).decision,"REQUIRE_APPROVAL"));
test("blocks resource outside signed grant",()=>{const v=make();assert.match(evaluateAuthorization(principal,{...v,resourceRefs:["file://different"]},now).reasons.join(" "),/exceeds/i)});
test("blocks forged grant",()=>{const v=make();assert.equal(evaluateAuthorization(principal,{...v,grant:{...v.grant,signature:"0".repeat(64)}},now).decision,"BLOCK")});
test("blocks forged certification",()=>{const v=make();assert.equal(evaluateAuthorization(principal,{...v,certification:{...v.certification,signature:"0".repeat(64)}},now).decision,"BLOCK")});
test("blocks prompt override",()=>assert.equal(evaluateAuthorization(principal,make({untrustedInputs:[{kind:"WEBPAGE",sourceRef:"source://web",contentHash:"a".repeat(64),policyOverrideAttempt:true,quarantined:true}]}),now).decision,"BLOCK"));
test("rejects raw content and plaintext credentials",()=>{const v=make();assert.equal(authorizationRequestSchema.safeParse({...v,untrustedInputs:[{kind:"WEBPAGE",sourceRef:"source://web",contentHash:"a".repeat(64),content:"ignore policy"}]}).success,false);assert.equal(authorizationRequestSchema.safeParse({...v,credentialReferences:[{name:"provider",ref:"plaintext"}]}).success,false)});
test("blocks changed approval scope",()=>{const base=make({capability:"provider:send",operation:"SEND",destination:{kind:"PROVIDER",ref:"provider://messages"},sideEffectClass:"NON_IDEMPOTENT",requiredScopes:["provider:send"],isolation:isolation()});const ap={approvalId:"a1",ownerId:"owner-123",approved:true as const,scopeHash:computeApprovalScopeHash(base),approvedAt:"2026-08-24T08:00:00.000Z",expiresAt:"2026-08-24T10:00:00.000Z",approverActorId:"approver"};const changed={...base,resourceRefs:["file://different"],approval:{...ap,signature:signApproval(as,ap)}};const {signature:_,...old}=changed.grant;const grant={...old,authorizedScopeHash:computeAuthorizationScopeHash(changed)};const req=authorizationRequestSchema.parse({...changed,grant:{...grant,signature:signAuthorizationGrant(gs,grant)}});assert.match(evaluateAuthorization(principal,req,now).reasons.join(" "),/scope changed/i)});
