import { createHmac, timingSafeEqual } from "node:crypto";
import type { NextFunction, Request, RequestHandler, Response } from "express";
import type { ZcosPrincipal } from "./contracts";
import { scopeAllows } from "./authorization-engine";
import { sha256, stableStringify } from "./redaction";

const principals = new WeakMap<Request, ZcosPrincipal>();
const usedNonces = new Map<string, number>();
const skew = 5 * 60 * 1000;
const header = (req: Request, name: string) => typeof req.headers[name] === "string" ? (req.headers[name] as string).trim() : "";
const split = (v: string) => [...new Set(v.split(",").map((x) => x.trim()).filter(Boolean))].sort();
const safeEqual = (a: string, b: string) => { const x = Buffer.from(a), y = Buffer.from(b); return x.length === y.length && timingSafeEqual(x, y); };
export type GatewaySignatureInput = { method: string; originalUrl: string; ownerId: string; actorId: string; roles: string; scopes: string; authenticatedAt: string; nonce: string; contentHash: string };
export function signaturePayload(input: GatewaySignatureInput): string { return ["zcos-auth-v1", input.method.toUpperCase(), input.originalUrl, input.ownerId, input.actorId, input.roles, input.scopes, input.authenticatedAt, input.nonce, input.contentHash].join("\n"); }
export const signGatewayRequest = (secret: string, input: GatewaySignatureInput) => createHmac("sha256", secret).update(signaturePayload(input)).digest("hex");
export function authenticateZcosRequest(req: Request, now = Date.now()): ZcosPrincipal {
  const secret = process.env.ZCOS_TRUSTED_GATEWAY_SECRET?.trim(); if (!secret) throw new Error("ZCOS trusted gateway authentication is unavailable");
  const ownerId = header(req, "x-zcos-owner-id"), actorId = header(req, "x-zcos-actor-id"), roles = header(req, "x-zcos-roles"), scopes = header(req, "x-zcos-scopes"), authenticatedAt = header(req, "x-zcos-auth-time"), nonce = header(req, "x-zcos-auth-nonce"), signature = header(req, "x-zcos-auth-signature").toLowerCase(), suppliedHash = header(req, "x-zcos-content-sha256").toLowerCase();
  if (!ownerId || !actorId || !authenticatedAt || !nonce || !signature || !suppliedHash) throw new Error("Authenticated ownership context is required");
  if (!/^[A-Za-z0-9._:-]{1,255}$/.test(ownerId) || !/^[A-Za-z0-9._:-]{1,255}$/.test(actorId) || !/^[A-Za-z0-9._:-]{8,255}$/.test(nonce)) throw new Error("Canonical authentication identifiers are invalid");
  const bodyHash = sha256(stableStringify(req.body ?? {})); if (!/^[a-f0-9]{64}$/.test(suppliedHash) || !safeEqual(suppliedHash, bodyHash)) throw new Error("Authenticated request body hash is invalid");
  const time = Date.parse(authenticatedAt); if (!Number.isFinite(time) || Math.abs(now - time) > skew) throw new Error("Authentication context is expired or not yet valid");
  for (const [key, expires] of usedNonces) if (expires <= now) usedNonces.delete(key); if (usedNonces.has(nonce)) throw new Error("Authentication context was replayed");
  const expected = signGatewayRequest(secret, { method: req.method, originalUrl: req.originalUrl, ownerId, actorId, roles, scopes, authenticatedAt, nonce, contentHash: bodyHash }); if (!safeEqual(signature, expected)) throw new Error("Authentication signature is invalid");
  usedNonces.set(nonce, now + skew); return { ownerId, actorId, roles: split(roles), scopes: split(scopes), authenticatedAt, nonce, authenticationMethod: "ZCOS_GATEWAY" };
}
export const setPrincipal = (req: Request, principal: ZcosPrincipal) => principals.set(req, principal);
export function getPrincipal(req: Request): ZcosPrincipal { const principal = principals.get(req); if (!principal) throw new Error("Authenticated principal is unavailable"); return principal; }
export function requirePrincipal(requirement: { scopes: string[]; roles?: string[] }): RequestHandler { return (req: Request, res: Response, next: NextFunction) => { try { const principal = authenticateZcosRequest(req); const missingScopes = requirement.scopes.filter((scope) => !scopeAllows(principal.scopes, scope)), missingRoles = (requirement.roles ?? []).filter((role) => !principal.roles.includes(role)); if (missingScopes.length || missingRoles.length) { void import("./integrity-audit").then(({ recordIntegrityEvent }) => recordIntegrityEvent({ principal, requestId: principal.nonce, traceId: principal.nonce, eventType: "AUTHORIZATION_DENIED", category: "AUTHORIZATION", severity: "HIGH", outcome: "UNAUTHORIZED", destination: req.path, summary: "An authenticated request lacked required ZCOS authority.", permissionScope: requirement.scopes, evidence: { method: req.method, route: req.path, missingScopes, missingRoles }, recovery: { action: "Request the missing authority through ZCOS Admin Access." } })).catch(() => undefined); return void res.status(403).json({ error: "AUTHORIZATION_DENIED", message: "The authenticated principal lacks required authority.", recovery: "Request the required ZCOS scope or role from Admin Access." }); } setPrincipal(req, principal); next(); } catch { void import("./integrity-audit").then(({ recordIntegrityEvent }) => recordIntegrityEvent({ requestId: header(req, "x-zcos-auth-nonce") || "authentication-denied", traceId: header(req, "x-zcos-auth-nonce") || "authentication-denied", eventType: "AUTHENTICATION_DENIED", category: "AUTHENTICATION", severity: "HIGH", outcome: "UNAUTHORIZED", destination: req.path, summary: "A protected request failed authenticated ownership verification.", evidence: { method: req.method, route: req.path }, recovery: { action: "Authenticate through ZCOS and submit a new signed request." } })).catch(() => undefined); res.status(401).json({ error: "AUTHENTICATION_REQUIRED", message: "The request does not carry a valid, current ZCOS authentication context.", recovery: "Return through ZCOS and authenticate again." }); } }; }
export function requireZenaIntegrationPrincipal(): RequestHandler { return (req, res, next) => { const configured = (process.env.ZENA_INTEGRATION_TOKEN ?? process.env.ZETA_SHARED_TOKEN)?.trim(), ownerId = process.env.ZENA_INTEGRATION_OWNER_ID?.trim(), supplied = header(req, "authorization").replace(/^Bearer\s+/i, "") || header(req, "x-zena-integration-token") || header(req, "x-zeta-integration-token"); if (!configured || !ownerId || !supplied || !safeEqual(configured, supplied)) return void res.status(401).json({ error: "INTEGRATION_AUTHENTICATION_DENIED", message: "The integration identity could not be verified.", recovery: "Reconnect through ZCOS Settings without placing credentials in the request body." }); setPrincipal(req, { ownerId, actorId: process.env.ZENA_INTEGRATION_ACTOR_ID?.trim() || "zcos-integration-service", roles: ["zcos-integration"], scopes: ["integrity:read", "integrity:monitoring:read"], authenticatedAt: new Date().toISOString(), nonce: `integration-${Date.now()}`, authenticationMethod: "ZENA_INTEGRATION" }); next(); }; }
export const isPlatformOwner = (principal: ZcosPrincipal) => principal.roles.includes("platform-owner") && scopeAllows(principal.scopes, "zcos:root");
export const resetAuthenticationReplayCacheForTests = () => usedNonces.clear();
