import { randomUUID } from "node:crypto";
import { storage } from "../storage";
import type { AuthorizationDecision, AuthorizationRequest, ExecutionResult, ZcosPrincipal } from "./contracts";
import { evaluateAuthorization } from "./authorization-engine";
import { recordIntegrityEvent } from "./integrity-audit";
import { redactProtectedData, sha256, stableStringify } from "./redaction";
import { duplicateExecutionDecision } from "./retry-safety";

export async function authorizeExecution(principal: ZcosPrincipal, request: AuthorizationRequest): Promise<AuthorizationDecision> {
  let decision = evaluateAuthorization(principal, request);
  if (decision.decision === "ALLOW") { const fingerprint = sha256(stableStringify({ ownerId: request.ownerId, capability: request.capability, operation: request.operation, resources: request.resourceRefs, destination: request.destination, scopeHash: decision.scopeHash })); const reservation = await storage.reserveExecutionRecord({ id: decision.executionId ?? randomUUID(), ownerId: principal.ownerId, actorId: principal.actorId, requestId: request.requestId, traceId: request.traceId, idempotencyKey: request.idempotencyKey, requestFingerprint: fingerprint, executionBindingHash: request.executionBinding ? sha256(stableStringify(request.executionBinding)) : undefined, approvalScopeHash: request.approval?.scopeHash, capability: request.capability, operation: request.operation, destination: request.destination.ref, sideEffectClass: request.sideEffectClass, riskLevel: decision.riskLevel, state: "PENDING", resultEvidence: {} }); if (!reservation.inserted) decision = duplicateExecutionDecision(reservation.record, fingerprint, decision.scopeHash); else decision.executionId = reservation.record.id; }
  const event = await recordIntegrityEvent({ principal, requestId: request.requestId, traceId: request.traceId, eventType: "EXECUTION_AUTHORIZATION_DECISION", category: decision.decision === "BLOCK" ? "AUTHORIZATION" : "EXECUTION", severity: decision.riskLevel, outcome: decision.decision, capability: request.capability, provider: request.provider, connector: request.connector, destination: request.destination.ref, summary: decision.decision === "ALLOW" ? "Execution passed ZENA security evaluation and received an idempotent reservation." : decision.decision === "REQUIRE_APPROVAL" ? "Execution requires approval bound to the evaluated scope." : "Execution was blocked by ZENA security evaluation.", permissionScope: request.requiredScopes, risk: { level: decision.riskLevel, reasons: decision.reasons }, evidence: { executionId: decision.executionId, scopeHash: decision.scopeHash, grantId: request.grant.grantId, isolationBoundary: request.isolation?.boundaryId, untrustedInputHashes: request.untrustedInputs.map((i) => i.contentHash), credentialReferenceNames: request.credentialReferences.map((c) => c.name) }, recovery: decision.recovery });
  if (decision.decision === "BLOCK" && decision.riskLevel === "CRITICAL") await storage.createIntegrityFinding({ id: randomUUID(), ownerId: principal.ownerId, severity: "CRITICAL", state: "ACTION_REQUIRED", title: "Critical execution request blocked", summary: decision.reasons.join(" "), affectedScope: { capability: request.capability, destination: request.destination.ref, executionId: decision.executionId }, evidenceEventIds: [event.id], recovery: decision.recovery });
  return decision;
}
export async function recordExecutionResult(principal: ZcosPrincipal, executionId: string, result: ExecutionResult) {
  const existing = await storage.getExecutionRecord(principal.ownerId, executionId);
  if (!existing || existing.actorId !== principal.actorId || existing.requestId !== result.requestId || existing.traceId !== result.traceId) { await recordIntegrityEvent({ principal, requestId: result.requestId, traceId: result.traceId, eventType: "EXECUTION_RESULT_REJECTED", category: "EXECUTION", severity: "HIGH", outcome: "BLOCKED", summary: "An execution result did not match an open reservation in the authenticated owner and actor scope.", evidence: { executionId }, recovery: { action: "Reconcile the originating request, trace, actor, and terminal evidence.", safeToRetry: false } }); return undefined; }
  const isUncertain = result.state === "PARTIAL" || result.state === "UNKNOWN" || result.providerOutcome === "UNKNOWN";
  const evidence = redactProtectedData({ providerOutcome: result.providerOutcome, sideEffects: result.sideEffects, verification: result.verification, recovery: { ...result.recovery, safeToRetry: isUncertain ? false : result.recovery.safeToRetry } }) as Record<string, unknown>;
  const updated = await storage.updateExecutionRecordState(principal.ownerId, executionId, result.state, evidence, { actorId: principal.actorId, expectedStates: ["PENDING", "RUNNING"] });
  if (!updated) { await recordIntegrityEvent({ principal, requestId: result.requestId, traceId: result.traceId, eventType: "DUPLICATE_EXECUTION_RESULT_BLOCKED", category: "EXECUTION", severity: "HIGH", outcome: "BLOCKED", capability: existing.capability, destination: existing.destination, summary: "A result attempted to replace an execution state that was no longer open.", evidence: { executionId, existingState: existing.state }, recovery: { action: "Use the preserved terminal result; do not repeat or overwrite the action.", safeToRetry: false } }); return undefined; }
  const event = await recordIntegrityEvent({ principal, requestId: result.requestId, traceId: result.traceId, eventType: "EXECUTION_RESULT_RECORDED", category: "EXECUTION", severity: isUncertain ? "HIGH" : result.state === "FAILED" ? "ATTENTION" : "INFO", outcome: result.state, capability: existing.capability, destination: existing.destination, summary: isUncertain ? "Execution has partial or unknown effects and is blocked from automatic retry." : `Execution reached terminal state ${result.state}.`, evidence, recovery: result.recovery });
  if (isUncertain) await storage.createIntegrityFinding({ id: randomUUID(), ownerId: principal.ownerId, severity: "HIGH", state: "ACTION_REQUIRED", title: "Execution effects require reconciliation", summary: "An execution reported partial or unknown effects. Automatic retry remains blocked.", affectedScope: { executionId, capability: existing.capability, destination: existing.destination }, evidenceEventIds: [event.id], recovery: evidence.recovery as Record<string, unknown> });
  return updated;
}
