import { randomUUID } from "node:crypto";
import type { Express, Request } from "express";
import { z } from "zod";
import { storage } from "../storage";
import { authorizationRequestSchema, executionResultSchema } from "../security/contracts";
import { asyncRoute } from "../security/async-route";
import { getPrincipal, isPlatformOwner, requirePrincipal } from "../security/authentication";
import { authorizeExecution, recordExecutionResult } from "../security/execution-security";
import { recordIntegrityEvent } from "../security/integrity-audit";
const read = requirePrincipal({ scopes: ["integrity:read"] }), evaluate = requirePrincipal({ scopes: ["integrity:evaluate"], roles: ["zcos-execution"] }), report = requirePrincipal({ scopes: ["integrity:execution:report"], roles: ["zcos-execution"] });
function owner(req: Request) { const principal = getPrincipal(req), requested = typeof req.query.ownerId === "string" ? req.query.ownerId.trim() : ""; if (!requested || requested === principal.ownerId) return principal.ownerId; return isPlatformOwner(principal) ? requested : undefined; }
async function invalid(req: Request, eventType: string, fields: string[], summary: string) { const principal = getPrincipal(req); await recordIntegrityEvent({ principal, requestId: principal.nonce, traceId: principal.nonce, eventType, category: "INPUT_SAFETY", severity: "HIGH", outcome: "BLOCKED", destination: req.path, summary, evidence: { invalidFields: fields }, recovery: { action: "Submit a complete typed reference-only request.", safeToRetry: false } }); }
export function registerIntegrityRoutes(app: Express) {
  app.post("/api/integrity/authorize", evaluate, asyncRoute(async (req, res) => { const parsed = authorizationRequestSchema.safeParse(req.body); if (!parsed.success) { const fields = [...new Set(parsed.error.issues.map((i) => i.path.join(".")))]; await invalid(req, "INVALID_SECURITY_REQUEST_BLOCKED", fields, "A security evaluation request was blocked at the strict typed boundary."); return void res.status(400).json({ error: "INVALID_SECURITY_REQUEST", message: "The request does not match the certified contract.", fields, recovery: "Submit typed references without raw credentials or untrusted content." }); } try { const decision = await authorizeExecution(getPrincipal(req), parsed.data); res.status(decision.decision === "BLOCK" ? 403 : decision.decision === "REQUIRE_APPROVAL" ? 409 : 200).json(decision); } catch { res.status(503).json({ error: "SECURITY_EVIDENCE_UNAVAILABLE", message: "The operation was not authorized because required evidence could not be preserved.", recovery: "Do not execute. Restore Integrity storage, then submit a new request." }); } }));
  app.post("/api/integrity/executions/:id/result", report, asyncRoute(async (req, res) => { const parsed = executionResultSchema.safeParse(req.body); if (!parsed.success) { await invalid(req, "INVALID_EXECUTION_RESULT_BLOCKED", parsed.error.issues.map((i) => i.path.join(".")), "An execution result omitted or violated required outcome evidence."); return void res.status(400).json({ error: "INVALID_EXECUTION_RESULT", recovery: "Report an explicit terminal, partial, cancelled, or unknown state with verification." }); } try { const record = await recordExecutionResult(getPrincipal(req), req.params.id, parsed.data); if (!record) return void res.status(409).json({ error: "EXECUTION_RESULT_REJECTED", message: "The result does not match an open execution in this owner and actor scope.", recovery: "Reconcile the request, trace, actor, and terminal evidence; do not retry the action." }); res.json({ executionId: record.id, state: record.state, updatedAt: record.updatedAt }); } catch { res.status(503).json({ error: "RESULT_EVIDENCE_UNAVAILABLE", message: "The result could not be preserved and must be treated as unknown.", recovery: "Do not repeat the action. Reconcile the destination first." }); } }));
  app.get("/api/integrity/logs", read, asyncRoute(async (req, res) => { const ownerId = owner(req); if (!ownerId) return void res.status(403).json({ error: "CROSS_OWNER_ACCESS_DENIED" }); const limit = z.coerce.number().int().min(1).max(500).catch(100).parse(req.query.limit); res.json(await storage.getIntegrityEvents(ownerId, limit, typeof req.query.outcome === "string" ? req.query.outcome : undefined)); }));
  app.get("/api/integrity/diagnostics", read, asyncRoute(async (req, res) => { const ownerId = owner(req); if (!ownerId) return void res.status(403).json({ error: "CROSS_OWNER_ACCESS_DENIED" }); const [findings, blocked, unauthorized, unknown] = await Promise.all([storage.getIntegrityFindings(ownerId), storage.getIntegrityEvents(ownerId, 50, "BLOCK"), storage.getIntegrityEvents(ownerId, 50, "UNAUTHORIZED"), storage.getIntegrityEvents(ownerId, 50, "UNKNOWN")]); res.json({ findings, checks: [{ id: "blocked", label: "Blocked operations", state: blocked.length ? "ATTENTION" : "CLEAR", count: blocked.length }, { id: "unauthorized", label: "Unauthorized attempts", state: unauthorized.length ? "ATTENTION" : "CLEAR", count: unauthorized.length }, { id: "unknown", label: "Unknown effects", state: unknown.length ? "ACTION_REQUIRED" : "CLEAR", count: unknown.length }], generatedAt: new Date().toISOString() }); }));
  app.get("/api/integrity/monitoring", read, asyncRoute(async (req, res) => { const ownerId = owner(req); if (!ownerId) return void res.status(403).json({ error: "CROSS_OWNER_ACCESS_DENIED" }); const [events, findings, executionStates] = await Promise.all([storage.getIntegrityEvents(ownerId, 25), storage.getIntegrityFindings(ownerId), storage.getExecutionStateCounts(ownerId)]); const unresolved = findings.filter((f) => !["RESOLVED", "ACCEPTED_RISK", "FALSE_POSITIVE"].includes(f.state)); res.json({ posture: unresolved.some((f) => f.severity === "CRITICAL") ? "CRITICAL" : unresolved.length ? "ATTENTION" : "CLEAR", unresolvedFindings: unresolved.length, criticalFindings: unresolved.filter((f) => f.severity === "CRITICAL").length, executionStates, recentEvents: events, observedAt: new Date().toISOString() }); }));
  app.post("/api/integrity/observations", requirePrincipal({ scopes: ["integrity:observe"] }), asyncRoute(async (req, res) => { const schema = z.object({ requestId: z.string().min(1).max(128), traceId: z.string().min(1).max(128), eventType: z.string().regex(/^[A-Z0-9_]{1,100}$/), severity: z.enum(["INFO", "ATTENTION", "HIGH", "CRITICAL"]), evidenceRefs: z.array(z.string().regex(/^[a-z][a-z0-9+.-]*:\/\/[A-Za-z0-9._:/-]+$/i)).max(50).default([]) }).strict(); const parsed = schema.safeParse(req.body); if (!parsed.success) { await invalid(req, "INVALID_OBSERVATION_BLOCKED", parsed.error.issues.map((i) => i.path.join(".")), "An observation was blocked at the strict evidence boundary."); return void res.status(400).json({ error: "INVALID_OBSERVATION", recovery: "Submit only a canonical event type and opaque evidence references." }); } const event = await recordIntegrityEvent({ principal: getPrincipal(req), requestId: parsed.data.requestId, traceId: parsed.data.traceId, eventType: parsed.data.eventType, category: "INTEGRITY", severity: parsed.data.severity, outcome: "OBSERVED", summary: `A typed ${parsed.data.eventType} observation was recorded.`, evidence: { evidenceRefs: parsed.data.evidenceRefs }, recovery: { action: "Route corrective action through ZCOS authorization." } }); res.status(201).json(event); }));
}
