import type { Express } from "express";
import { z } from "zod";
import { storage } from "../storage";
import { badActorService } from "../services/bad-actor-service";
import { firewallService } from "../services/firewall-service";
import { zenaIntegrityCore } from "../services/zena-integrity-core";
import { asyncRoute } from "../security/async-route";
import { getPrincipal, requirePrincipal, requireZenaIntegrationPrincipal } from "../security/authentication";
import { requireExecutionReservation } from "../security/execution-reservation";
const integrityRead = requirePrincipal({ scopes: ["integrity:read"] }), rootRead = requirePrincipal({ scopes: ["zcos:root:security:read"], roles: ["platform-owner"] }), rootWrite = requirePrincipal({ scopes: ["zcos:root:security:write"], roles: ["platform-owner"] });
const opaque = z.string().max(512).regex(/^[a-z][a-z0-9+.-]*:\/\/[A-Za-z0-9._:/-]+$/i);
export function registerSecurityRoutes(app: Express) {
  app.get("/api/firewall/public-status", (_req, res) => res.json({ system: "ZENA Control", status: "available", desk: "Integrity", surfaces: ["Logs", "Diagnostics", "Monitoring"], timestamp: new Date().toISOString() }));
  app.get("/api/integration/firewall/status", requireZenaIntegrationPrincipal(), asyncRoute(async (req, res) => res.json({ system: "FanFI / Fantasma Firewall", zena: await zenaIntegrityCore.getStatus(getPrincipal(req).ownerId), timestamp: new Date().toISOString() })));
  app.get("/api/dashboard/status", integrityRead, asyncRoute(async (req, res) => { const p = getPrincipal(req); const [zena, securityEvents, findings] = await Promise.all([zenaIntegrityCore.getStatus(p.ownerId), storage.getIntegrityEvents(p.ownerId, 20), storage.getIntegrityFindings(p.ownerId, 20)]); res.json({ zena, securityEvents, findings, timestamp: new Date().toISOString() }); }));
  app.get("/api/security-events", integrityRead, asyncRoute(async (req, res) => { res.setHeader("Deprecation", "true"); res.json(await storage.getIntegrityEvents(getPrincipal(req).ownerId, 50)); }));
  app.post("/api/security-events", integrityRead, (_req, res) => res.status(410).json({ error: "LEGACY_MUTATION_RETIRED", recovery: "Use typed Integrity observations or authorization." }));
  app.patch("/api/security-events/:id/status", integrityRead, (_req, res) => res.status(410).json({ error: "APPEND_ONLY_EVIDENCE", recovery: "Record a new resolution event." }));
  app.get("/api/zena-core/status", integrityRead, asyncRoute(async (req, res) => res.json(await zenaIntegrityCore.getStatus(getPrincipal(req).ownerId))));
  app.get("/api/zeta-core/status", (_req, res) => res.redirect(308, "/api/zena-core/status"));
  app.post("/api/zeta-core/analyze", integrityRead, (_req, res) => res.status(410).json({ error: "RAW_ANALYSIS_ROUTE_RETIRED", recovery: "Quarantine and classify input, then submit references and hashes." }));
  app.get("/api/threat-patterns", rootRead, asyncRoute(async (_req, res) => res.json(await storage.getThreatPatterns())));
  app.get("/api/zwap-protection", rootRead, asyncRoute(async (_req, res) => res.json(await storage.getZwapProtectionStatus())));
  app.get("/api/encryption-layers", rootRead, asyncRoute(async (_req, res) => res.json(await storage.getEncryptionLayers())));
  app.get("/api/network-nodes", rootRead, asyncRoute(async (_req, res) => res.json(await storage.getNetworkNodes())));
  app.get("/api/firewall/counters", rootRead, (_req, res) => res.json(firewallService.getThreatCounters()));
  app.get("/api/bad-actors", rootRead, asyncRoute(async (_req, res) => res.json(await storage.getBadActors())));
  app.get("/api/data-deprecation", rootRead, asyncRoute(async (_req, res) => res.json(await storage.getActiveDeprecations())));
  app.get("/api/quantum-protocols", rootRead, asyncRoute(async (_req, res) => res.json(await storage.getQuantumProtocols())));
  app.get("/api/threat-mitigation/status", rootRead, asyncRoute(async (_req, res) => res.json(await badActorService.getActiveThreatMitigationStatus())));
  app.patch("/api/zwap-protection/:id", rootWrite, requireExecutionReservation("zena.legacy.zwap-protection.update"), asyncRoute(async (req, res) => { const parsed = z.object({ status: z.enum(["SECURE", "VULNERABLE", "UNDER_ATTACK"]), integrityScore: z.number().int().min(0).max(100) }).strict().safeParse(req.body); if (!parsed.success) return void res.status(400).json({ error: "INVALID_PROTECTION_UPDATE" }); const updated = await storage.updateZwapProtection(Number(req.params.id), parsed.data.status, parsed.data.integrityScore); if (!updated) return void res.status(404).json({ error: "PROTECTION_COMPONENT_NOT_FOUND" }); res.json(updated); }));
  app.post("/api/firewall/detect-threat", rootWrite, requireExecutionReservation("zena.legacy.firewall.detect"), asyncRoute(async (req, res) => { const parsed = z.object({ sourceRef: opaque, targetRef: opaque, threatType: z.string().min(1).max(100) }).strict().safeParse(req.body); if (!parsed.success) return void res.status(400).json({ error: "INVALID_THREAT_OBSERVATION" }); res.json({ detected: await firewallService.detectThreat(parsed.data.sourceRef, parsed.data.targetRef, parsed.data.threatType) }); }));
  app.post("/api/bad-actors/detect", rootWrite, requireExecutionReservation("zena.legacy.actor.detect"), asyncRoute(async (req, res) => { const parsed = z.object({ identifierRef: opaque, identifierType: z.enum(["IP_ADDRESS", "WALLET", "DEVICE_ID", "EMAIL"]), threatIndicators: z.object({ suspiciousActivity: z.boolean().optional(), repeatedAccess: z.boolean().optional(), unauthorizedAttempts: z.number().int().min(0).max(100).optional(), dataExfiltration: z.boolean().optional() }).strict().default({}) }).strict().safeParse(req.body); if (!parsed.success) return void res.status(400).json({ error: "INVALID_ACTOR_OBSERVATION" }); res.json(await badActorService.detectAndTrackBadActor(parsed.data.identifierRef, parsed.data.identifierType, parsed.data.threatIndicators)); }));
  app.post("/api/bad-actors/:id/escalate", rootWrite, requireExecutionReservation("zena.legacy.actor.escalate"), asyncRoute(async (req, res) => { const actor = (await storage.getBadActors()).find((x) => x.id === Number(req.params.id)); if (!actor) return void res.status(404).json({ error: "ACTOR_NOT_FOUND" }); res.json(await storage.escalateBadActor(actor.identifier)); }));
  app.post("/api/bad-actors/:id/deploy-countermeasures", rootWrite, (_req, res) => res.status(410).json({ error: "UNCERTIFIED_COUNTERMEASURE_RETIRED", recovery: "Route real containment through ZCOS approval and ZENA execution security." }));
}
